services:
  dotnet-dev:
    image:
      dotnet-dev-container:2.0-v9
    volumes:
      - /home/peter/.config/nvim:/home/dev/.config/nvim:Z
      - /home/peter/learning/c#:/home/dev/mnt/c#:Z
      - /home/peter/learning/adventofcode/:/home/dev/mnt/adventofcode:Z
      - /home/peter/tools/development/boardball/:/home/dev/mnt/boardball:Z
      - /home/peter/egyetem/szofi/:/home/dev/mnt/szofi:Z
    command: tail -f /dev/null
